# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.12.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"
